### ISSUE TITLE
Design User Personas

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage-frontend#3]
User with Mental Illness
Caregiver
Researchers
McKoy Creative
Neighbor

Design one persona and check with at least two team members before moving forward with the rest

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jTFlfYW9kSnU2ZG8 The personas. The one still needs a motivation I'll fill it in today.

**Comment by wonderwoman13** [comment]
These are awesome, @jwaltrowski! Brooke's motivations should include that she feels that she can't relate with her peers since they don't know about her condition. She is eager to be accepted and feel included. 

"Low resourcs" => "Low time and monetary resources" on Pam (typo)

**Comment by jwaltrowski** [comment]
Awesome! Thank you.

**Comment by Iamjacksplasmid** [comment]
Heya guys!  Here's my notes:

* I'm seeing "User w/ Illness" (Brooke), "Family/Loved One" (John), "McKoy" (Jason), "Researcher" (Pam), and "Neighbor" (Michael), but I don't see anybody for "Caregiver".  Is John supposed to be the Caregiver persona?
* Two periods at the end of Jason's quote.
* In Michael's motivations, "knowledgealbe"
* Space before period in Pam's quote.  In her motivations, "mental health which as also been a barrier to acquiring relieble" should be changed to "mental health, which has also been a barrier to acquiring reliable".  In her frustrations, "Low resourcs" should be "Low resources"
* Instead of "Contextual Camouflage" above the Persona name, could we get the user type that they represent?  Basically just the categories Britt listed in the first post.
* Final thing, a bit nitpicky, tell me to eff off if you want, but the spacing between the header and body text is different for "Motivations", "Goals", and "Frustrations".  I think it would look cleaner if the headers stay where they are, but the body text on "Motivations" and "Goals" moves down so that it is the same distance from its header as it is in "Frustrations".

Besides those things, fantastic work!  They're short, sweet, and capture the essence of each user type well.

**Comment by jwaltrowski** [comment]
@Iamjacksplasmid thank you so much! I will fix all of that! And Yes, Caregiver is the person with the relationship.

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jTFlfYW9kSnU2ZG8

I fixed everything both @Iamjacksplasmid and @wonderwoman13 mentioned and I added John's Motivation.  Let me know if anything else needs fixed.  Thanks for spotting all those corrections, I never would have found them!

**Comment by wonderwoman13** [comment]
@jwaltrowski response back from Jason: 
"therealmckoy [2:52 PM] 
These are dope! Would it be prudent to also include a "troll" persona who initially wanted to use the app to be a jerk but then found out all the info on how stigma affects people and had a change of heart? Actually walked away learning something; an epiphany?"

Can you add another user persona to your plate?

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jTFlfYW9kSnU2ZG8 Here's the internet troll.

**Comment by wonderwoman13** [comment]
Complete!
